In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [3]:
def Diagonalizar(A_, ones = False):
    
    A = A_.copy()
    n = A.shape[0]
    
    for i in range(n):
        
        if ones:
            A[i,:] /= A[i,i]
        
        
        for j in range(i+1,n):
            
            a = A[j,i]/A[i,i]
            A[j,:] -= a*A[i,:]
            
    return A

In [4]:
Diagonalizar(M,True)

array([[ 1.        , -0.33333333, -0.33333333],
       [ 0.        ,  1.        ,  0.25      ],
       [ 0.        ,  0.        ,  1.        ]])

$$  x_{i} = \frac{ b_{i}  - \sum_{j=i+1}^{n} A_{i,j}x_{j} }{ A_{ii}  }  $$ 

In [5]:
def GausJordan(A_,b_,ones = False):
    
    A = A_.copy()
    b = b_.copy()
    
    n = A.shape[0]
    
    for i in range(n):
        
        if ones:
            b[i] /= A[i,i]
            A[i,:] /= A[i,i]
           
        
        for j in range(i+1,n):
            
            a = A[j,i]/A[i,i]
            A[j,:] -= a*A[i,:]
            b[j] -= a*b[i]
         
       
    x = np.zeros_like(b)

    
    for i in reversed(range(n)):
        #print(i)
    
        x[i] = b[i]
        
        for j in range( i+1, n ):
            x[i] -= A[i,j]*x[j]
        
        if not ones:
            x[i] /= A[i,i]
    
    return x,A,b

In [8]:
x,A,b_ = GausJordan(M,b,ones=True)

In [9]:
x

array([1., 1., 1.])