In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [ ]:
def Diagonalizar(A_, ones = False):
    
    A = A_.copy()
    n = A.shape[0]
    
    for i in range(n):
        