In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [4]:
np.linalg.solve(M,b)

array([1., 1., 1.])

In [12]:
def GetacobiMethod(A,b,itmax=100,error = 1e-10):
    
    M,N = A.shape
    
    x = np.zeros(N)
    
    sumk = np.zeros_like(x)
    
    it = 0
    
    residuo = np.linalg.norm( b - np.dot(A,x) )
    
    while ( residuo > error and it < itmax ):
        
        it += 1
        
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += A[i][j]*x[j]
            sumk[i] = sum_
          
        for i in range(M):
            
            if A[i,i] != 0:
                x[i] = (b[i] - sumk[i])/A[i,i]
            else:
                print('No invertible con Jacobi')
        
        print(x)
        residuo = np.linalg.norm( b - np.dot(A,x) )
        
    return x,it,residuo

In [14]:
Xsol,it,error = GetacobiMethod(M,b)

[0.33333333 1.         1.75      ]
[1.25       0.52777778 1.33333333]
[0.9537037  0.97222222 0.99305556]
[0.98842593 0.98688272 1.03009259]
[1.00565844 0.98611111 1.00906636]
[0.99839249 0.99886403 1.000643  ]
[0.99983568 0.99924983 1.00108775]
[1.00011253 0.99958264 1.0002697 ]
[0.99995078 0.99994761 1.00004808]
[0.99999856 0.99996757 1.00003771]
[1.00000176 0.99998695 1.00000883]
[0.99999859 0.99999764 1.00000238]
[1.00000001 0.99999874 1.00000129]
[1.00000001 0.99999957 1.00000031]
[0.99999996 0.9999999  1.0000001 ]
[1.         0.99999995 1.00000004]
[1.         0.99999999 1.00000001]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]


In [15]:
Xsol, print(it,error)

23 5.690579155224868e-11


(array([1., 1., 1.]), None)