In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [4]:
np.linalg.solve(M,b)

array([1., 1., 1.])

In [18]:
def GetacobiMethod(A,b,itmax=1000,error = 1e-10):
    
    M,N = A.shape
    
    x = np.zeros(N)
    
    sumk = np.zeros_like(x)
    
    x = [13,20,-1]
    
    it = 0
    
    residuo = np.linalg.norm( b - np.dot(A,x) )
    
    while ( residuo > error and it < itmax ):
        
        it += 1
        
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += A[i][j]*x[j]
            sumk[i] = sum_
          
        for i in range(M):
            
            if A[i,i] != 0:
                x[i] = (b[i] - sumk[i])/A[i,i]
            else:
                print('No invertible con Jacobi')
        
        print(x)
        residuo = np.linalg.norm( b - np.dot(A,x) )
        
    return x,it,residuo

In [19]:
Xsol,it,error = GetacobiMethod(M,b)

[6.666666666666667, 5.666666666666667, -9.75]
[-1.0277777777777777, 6.472222222222222, -3.0]
[1.4907407407407407, 1.6574074074074074, 0.6458333333333333]
[1.10108024691358, 1.2816358024691359, 0.5902777777777777]
[0.9573045267489713, 1.170267489711934, 0.879050925925926]
[1.0164394718792866, 1.0260845336076818, 0.9787808641975309]
[1.0016217992684042, 1.012552869227252, 0.9852591306584362]
[0.9992706666285628, 1.0054542228699894, 0.9960508830589849]
[1.0005017019763247, 1.0010732611898592, 0.9990011109682213]
[1.0000247907193602, 1.0005001970027012, 0.9994808337143728]
[0.9999936769056914, 1.0001813190016626, 0.9998625553896445]
[1.0000146247971025, 1.0000437071720156, 0.9999578317967386]
[1.0000005129895848, 1.0000189310001213, 0.9999817608084449]
[1.0000002306028553, 1.0000062507270466, 0.9999950107551773]
[1.0000004204940747, 1.000001739949226, 0.9999983220168107]
[1.0000000206553457, 1.0000006994924213, 0.9999993547656562]
[1.0000000180860258, 1.0000002219632298, 0.9999998147992218

In [20]:
Xsol, print(it,error)

26 3.3674979755715494e-11


([1.0000000000012628, 1.0000000000109328, 0.9999999999902489], None)